#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTA_DM_COD {0x1A, 0x01, 0x14}

#define BTA_DISABLE_DELAY 1000

#define BTM_DEF_LOCAL_NAME   "Aquaris M8"
#define BTA_AV_MAX_A2DP_MTU  1788
#define BLE_INCLUDED TRUE
#define BTA_GATT_INCLUDED TRUE
#define SMP_INCLUDED TRUE

/* #define KERNEL_MISSING_CLOCK_BOOTTIME_ALARM TRUE */

#endif
